# Generated by Django 4.2.1 on 2023-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendly", "0004_alter_event_expired_alter_event_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expired",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
