# Generated by Django 4.2.1 on 2023-05-10 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendly", "0009_alter_event_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="url",
            new_name="hash_url",
        ),
    ]
