# Generated by Django 4.2.1 on 2023-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendly", "0010_rename_url_event_hash_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
