# Generated by Django 4.2.1 on 2023-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendly", "0011_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
