# Generated by Django 4.2.1 on 2023-05-18 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendly", "0013_alter_event_hash_url_alter_event_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="user_created",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
