# Generated by Django 4.2.1 on 2023-06-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendly", "0014_alter_event_user_created_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_amount_of_joiners",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="EventJoinUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="calendly.event"),
                ),
            ],
        ),
    ]
